server {
    listen 80;
    server_name rippository.bioinformatics.nl;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name rippository.bioinformatics.nl;

    # SSL certificate paths 
    # ssl_certificate     /etc/ssl/certs/rippository.bioinformatics.nl.crt;
    # ssl_certificate_key /etc/ssl/private/rippository.bioinformatics.nl.key;

    location /api/ {
        proxy_pass http://localhost:4144;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /export/ {
        proxy_pass http://localhost:4146;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /similarity/ {
        proxy_pass http://localhost:4145;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://localhost:4147;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
